# Generated by Django 3.2.4 on 2021-06-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid19',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_ch', models.CharField(max_length=255)),
                ('country_en', models.CharField(max_length=255)),
                ('cases', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'backend_covid19',
                'managed': True,
            },
        ),
    ]
